# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChangePassword.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector
my_db = mysql.connector.connect(host="localhost",
                                user="root",
                                passwd="RunningMan7012",
                                database="ils",
                                autocommit=True)
my_cursor = my_db.cursor()

class Ui_MainWindow(object):
    def __init__(self,MainWindow,emailid,memberhome):
        self.emailid = emailid
        self.memberhome = memberhome
        self.MainWindow = MainWindow
        self.setupUi(self.MainWindow)
        self.MainWindow.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1059, 612)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.resetPasswordBtn = QtWidgets.QPushButton(self.centralwidget)
        self.resetPasswordBtn.setGeometry(QtCore.QRect(410, 430, 241, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetPasswordBtn.sizePolicy().hasHeightForWidth())
        self.resetPasswordBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.resetPasswordBtn.setFont(font)
        self.resetPasswordBtn.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid #536DFE;\n"
"color: white;\n"
"background-color: #536DFE;\n"
"text-align: center;\n"
"padding-bottom: 4px;")
        self.resetPasswordBtn.setObjectName("resetPasswordBtn")
        self.login_newPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.login_newPassword.setGeometry(QtCore.QRect(410, 350, 241, 31))
        self.login_newPassword.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid white;")
        self.login_newPassword.setAlignment(QtCore.Qt.AlignCenter)
        self.login_newPassword.setObjectName("login_newPassword")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(340, 230, 371, 71))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(32)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.home_heroImage = QtWidgets.QLabel(self.centralwidget)
        self.home_heroImage.setGeometry(QtCore.QRect(0, 0, 1061, 600))
        self.home_heroImage.setStyleSheet("\n"
"background-image: url(:/Assets/assets/ForgetPassword.png);")
        self.home_heroImage.setText("")
        self.home_heroImage.setObjectName("home_heroImage")
        self.login_newConfirmPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.login_newConfirmPassword.setGeometry(QtCore.QRect(410, 390, 241, 31))
        self.login_newConfirmPassword.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid white;")
        self.login_newConfirmPassword.setAlignment(QtCore.Qt.AlignCenter)
        self.login_newConfirmPassword.setObjectName("login_newConfirmPassword")
        self.welcomeTitle = QtWidgets.QLabel(self.centralwidget)
        self.welcomeTitle.setGeometry(QtCore.QRect(800, 10, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.welcomeTitle.setFont(font)
        self.welcomeTitle.setStyleSheet("border-radius: 5px;\n"
"background-color: transparent;\n"
"color:white;")
        self.welcomeTitle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.welcomeTitle.setObjectName("welcomeTitle")
        self.login_userid = QtWidgets.QLineEdit(self.centralwidget)
        self.login_userid.setGeometry(QtCore.QRect(410, 310, 241, 31))
        self.login_userid.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid white;")
        self.login_userid.setAlignment(QtCore.Qt.AlignCenter)
        self.login_userid.setObjectName("login_userid")
        self.home_heroImage.raise_()
        self.resetPasswordBtn.raise_()
        self.login_newPassword.raise_()
        self.label_3.raise_()
        self.login_newConfirmPassword.raise_()
        self.welcomeTitle.raise_()
        self.login_userid.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Button Assignment
        self.resetPasswordBtn.clicked.connect(lambda: self.verifyandclose())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.resetPasswordBtn.setText(_translate("MainWindow", "Reset Password"))
        self.login_newPassword.setPlaceholderText(_translate("MainWindow", "Enter new password"))
        self.label_3.setText(_translate("MainWindow", "Change Password"))
        self.login_newConfirmPassword.setPlaceholderText(_translate("MainWindow", "Reconfirm password"))
        self.welcomeTitle.setText(_translate("MainWindow", ""))
        self.login_userid.setPlaceholderText(_translate("MainWindow", "Enter your email"))

    # Button Assigment
    def verifyandclose(self):
        if self.memberhome == "":
            if self.login_userid.text() == "" or self.login_newPassword.text() == "" or self.login_newConfirmPassword.text() == "":
                self.error_popup_fill_fields()
            elif self.login_newPassword.text() != self.login_newConfirmPassword.text():
                self.error_popup_password_confirm()
            elif self.login_userid.text() != self.emailid:
                self.error_popup_email_confirm()
            else:
                my_cursor.execute("UPDATE LibraryUser SET password = %s WHERE userId = %s;",(self.login_newPassword.text(),self.login_userid.text()))
                my_db.commit()
                self.password_reset_popup()
                self.MainWindow.close()
        else:
            if self.login_userid.text() == "" or self.login_newPassword.text() == "" or self.login_newConfirmPassword.text() == "":
                self.error_popup_fill_fields()
            elif self.login_newPassword.text() != self.login_newConfirmPassword.text():
                self.error_popup_password_confirm()
            elif self.login_userid.text() != self.emailid:
                self.error_popup_email_confirm()
            else:
                my_cursor.execute("UPDATE LibraryUser SET password = %s WHERE userId = %s;",
                                  (self.login_newPassword.text(), self.login_userid.text()))
                my_db.commit()
                self.password_reset_popup()
                self.memberhome.load_account_details(self.emailid)
                self.MainWindow.close()

    # Miscellaneous
    def error_popup_fill_fields(self):
        msg = QtWidgets.QMessageBox()
        msg.setWindowTitle("Error")
        msg.setText("Please fill up all fields")
        msg.setIcon(QtWidgets.QMessageBox.Critical)
        msg.exec_()

    def error_popup_password_confirm(self):
        msg = QtWidgets.QMessageBox()
        msg.setWindowTitle("Error")
        msg.setText("Please ensure your passwords are the same")
        msg.setIcon(QtWidgets.QMessageBox.Critical)
        msg.exec_()

    def error_popup_email_confirm(self):
        msg = QtWidgets.QMessageBox()
        msg.setWindowTitle("Error")
        msg.setText("Please ensure you have correctly entered your email")
        msg.setIcon(QtWidgets.QMessageBox.Critical)
        msg.exec_()

    def password_reset_popup(self):
        msg = QtWidgets.QMessageBox()
        msg.setWindowTitle("Notice")
        msg.setText("Your Password has been reset")
        msg.setIcon(QtWidgets.QMessageBox.Information)
        msg.exec_()

import background_image

