# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MakePayment.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector


my_db = mysql.connector.connect(host="localhost",
                                user="root",
                                passwd="RunningMan7012",
                                database="ils",
                                autocommit=True)

my_cursor = my_db.cursor()

class Ui_MainWindow(object):
    def __init__(self,MainWindow,amount,emailid,loginWindow,memberHome):
        self.memberHome = memberHome
        self.MainWindow = MainWindow
        self.amount = "Payment Amount : $" + str(amount)
        self.actual_amount = int(float(amount))
        self.emailid = emailid
        self.loginWindow = loginWindow
        self.setupUi(self.MainWindow)
        self.MainWindow.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1059, 612)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(380, 230, 311, 71))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(32)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.register_heroImage = QtWidgets.QLabel(self.centralwidget)
        self.register_heroImage.setGeometry(QtCore.QRect(0, 0, 1061, 600))
        self.register_heroImage.setStyleSheet("background-image: url(:/Assets/assets/CreatePassword.png);")
        self.register_heroImage.setText("")
        self.register_heroImage.setObjectName("register_heroImage")
        self.login_password = QtWidgets.QLineEdit(self.centralwidget)
        self.login_password.setGeometry(QtCore.QRect(410, 470, 241, 31))
        self.login_password.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid white;")
        self.login_password.setAlignment(QtCore.Qt.AlignCenter)
        self.login_password.setObjectName("login_password")
        self.createAccountBtn = QtWidgets.QPushButton(self.centralwidget)
        self.createAccountBtn.setGeometry(QtCore.QRect(410, 510, 241, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createAccountBtn.sizePolicy().hasHeightForWidth())
        self.createAccountBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.createAccountBtn.setFont(font)
        self.createAccountBtn.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid  rgb(255, 0, 0);\n"
"color: white;\n"
"background-color: #ff445c;\n"
"text-align: center;\n"
"padding-bottom: 4px;")
        self.createAccountBtn.setObjectName("createAccountBtn")
        self.login_email = QtWidgets.QLineEdit(self.centralwidget)
        self.login_email.setGeometry(QtCore.QRect(410, 350, 241, 31))
        self.login_email.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid white;")
        self.login_email.setAlignment(QtCore.Qt.AlignCenter)
        self.login_email.setObjectName("login_email")
        self.login_username = QtWidgets.QLineEdit(self.centralwidget)
        self.login_username.setGeometry(QtCore.QRect(410, 390, 241, 31))
        self.login_username.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid white;")
        self.login_username.setAlignment(QtCore.Qt.AlignCenter)
        self.login_username.setObjectName("login_username")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(410, 430, 111, 31))
        self.dateEdit.setStyleSheet("border-radius: 7px;")
        self.dateEdit.setObjectName("dateEdit")
        self.login_password_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.login_password_2.setGeometry(QtCore.QRect(520, 430, 131, 31))
        self.login_password_2.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid white;")
        self.login_password_2.setText("")
        self.login_password_2.setAlignment(QtCore.Qt.AlignCenter)
        self.login_password_2.setObjectName("login_password_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(410, 300, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid #536DFE;\n"
"background-color: #536DFE;\n"
"color:white;")
        self.label.setObjectName("label")
        self.welcomeTitle = QtWidgets.QLabel(self.centralwidget)
        self.welcomeTitle.setGeometry(QtCore.QRect(800, 10, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.welcomeTitle.setFont(font)
        self.welcomeTitle.setStyleSheet("border-radius: 5px;\n"
"background-color: transparent;\n"
"color:white;")
        self.welcomeTitle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.welcomeTitle.setObjectName("welcomeTitle")
        self.reservation_cancelReservation = QtWidgets.QPushButton(self.centralwidget)
        self.reservation_cancelReservation.setGeometry(QtCore.QRect(20, 510, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.reservation_cancelReservation.setFont(font)
        self.reservation_cancelReservation.setStyleSheet("border: 2px solid white;\n"
"border-radius: 5px;\n"
"background-color: white;\n"
"color: black;\n"
"font-weight: bold;\n"
"padding-bottom: 2px;\n"
"")
        self.reservation_cancelReservation.setObjectName("reservation_cancelReservation")
        self.register_heroImage.raise_()
        self.label_3.raise_()
        self.login_password.raise_()
        self.createAccountBtn.raise_()
        self.login_email.raise_()
        self.login_username.raise_()
        self.dateEdit.raise_()
        self.login_password_2.raise_()
        self.label.raise_()
        self.welcomeTitle.raise_()
        self.reservation_cancelReservation.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #Button Assignment
        self.reservation_cancelReservation.clicked.connect(lambda: self.backtohome())
        self.createAccountBtn.clicked.connect(lambda: self.pay())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Make Payment"))
        self.login_password.setPlaceholderText(_translate("MainWindow", "Zip Code"))
        self.createAccountBtn.setText(_translate("MainWindow", "Pay"))
        self.login_email.setPlaceholderText(_translate("MainWindow", "Name on Card"))
        self.login_username.setPlaceholderText(_translate("MainWindow", "Card Number"))
        self.login_password_2.setPlaceholderText(_translate("MainWindow", "CVC"))
        self.label.setText(_translate("MainWindow", self.amount))
        self.welcomeTitle.setText(_translate("MainWindow", " "))
        self.reservation_cancelReservation.setText(_translate("MainWindow", "Back to Home"))

    # Button functions
    def backtohome(self):
        self.memberHome.load_fines(self.emailid)
        self.memberHome.MainWindow.show()
        self.MainWindow.close()

    def pay(self):
        if self.login_email.text() == "" or self.login_username.text() == "" or self.login_password_2.text() == "" or self.login_password == "":
            self.error_popup_fill_fields()
        else:
            my_cursor.execute("INSERT INTO Payment (paidAmount, date, userId) "
                              "VALUES (%s, CURRENT_TIMESTAMP(), %s);",(self.actual_amount,self.emailid))
            my_db.commit()
            my_cursor.execute("DELETE FROM Fine WHERE userId = %s;",(self.emailid,))
            my_db.commit()
            self.backtohome()


    def error_popup_fill_fields(self):
        msg = QtWidgets.QMessageBox()
        msg.setWindowTitle("Error")
        msg.setText("Please fill up all fields")
        msg.setIcon(QtWidgets.QMessageBox.Critical)
        msg.exec_()

import background_image



