# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ResetPassword.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ChangePassword import Ui_MainWindow as changepassword
import mysql.connector
my_db = mysql.connector.connect(host="localhost",
                                user="root",
                                passwd="RunningMan7012",
                                database="ils",
                                autocommit=True)
my_cursor = my_db.cursor()

class Ui_MainWindow(object):
    def __init__(self,MainWindow):
        self.MainWindow = MainWindow
        self.setupUi(self.MainWindow)
        self.MainWindow.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1059, 612)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.resetPasswordBtn = QtWidgets.QPushButton(self.centralwidget)
        self.resetPasswordBtn.setGeometry(QtCore.QRect(410, 360, 241, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetPasswordBtn.sizePolicy().hasHeightForWidth())
        self.resetPasswordBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.resetPasswordBtn.setFont(font)
        self.resetPasswordBtn.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid #536DFE;\n"
"color: white;\n"
"background-color: #536DFE;\n"
"text-align: center;\n"
"padding-bottom: 4px;")
        self.resetPasswordBtn.setObjectName("resetPasswordBtn")
        self.reset_email = QtWidgets.QLineEdit(self.centralwidget)
        self.reset_email.setGeometry(QtCore.QRect(410, 320, 241, 31))
        self.reset_email.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid white;")
        self.reset_email.setAlignment(QtCore.Qt.AlignCenter)
        self.reset_email.setObjectName("reset_email")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(310, 240, 431, 71))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(32)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.resetPassword_heroImage = QtWidgets.QLabel(self.centralwidget)
        self.resetPassword_heroImage.setGeometry(QtCore.QRect(0, 0, 1061, 600))
        self.resetPassword_heroImage.setStyleSheet("background-image: url(:/Assets/assets/ForgetPassword.png)")
        self.resetPassword_heroImage.setText("")
        self.resetPassword_heroImage.setObjectName("resetPassword_heroImage")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(800, 10, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-radius: 5px;\n"
"background-color: transparent;\n"
"color:white;")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.resetPassword_heroImage.raise_()
        self.resetPasswordBtn.raise_()
        self.reset_email.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Button Assignment
        self.resetPasswordBtn.clicked.connect(lambda: self.show_ChangePassword_window())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.resetPasswordBtn.setText(_translate("MainWindow", "Change Password"))
        self.reset_email.setPlaceholderText(_translate("MainWindow", "Enter email"))
        self.label_3.setText(_translate("MainWindow", "Reset Password"))
        self.label_2.setText(_translate("MainWindow", ""))

    def show_ChangePassword_window(self):
        my_cursor.execute("SELECT userId 'User ID' FROM LibraryUser WHERE userId = %s;",(self.reset_email.text(),))
        rows = my_cursor.fetchall()
        if rows == []:
            self.error_popup_valid_userid()
        else:
            self.window = QtWidgets.QMainWindow()
            changepassword(self.window,self.reset_email.text(),"")
            self.MainWindow.close()

    def error_popup_valid_userid(self):
        msg = QtWidgets.QMessageBox()
        msg.setWindowTitle("Error")
        msg.setText("Please enter a valid email")
        msg.setIcon(QtWidgets.QMessageBox.Critical)
        msg.exec_()
import background_image



