/*
--------------------------------------------
DATA MANAGEMENT AND VISUALISATION (BT2102)
GROUP 10 BT2102 ASSIGNMENT 1
INSERT OF BOOK TABLE 
LAST EDITED: 27/03/2021

Convert CSV to SQL
https://www.convertcsv.com/csv-to-sql.htm
--------------------------------------------
*/


/* POPULATION OF BOOK TABLE */
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (1,'1933988673','Unlocking Android','[''W. Frank Ableson'', ''Charlie Collins'', ''Robi Sen'']','[''Open Source'', ''Mobile'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (2,'1935182722','Android in Action, Second Edition','[''W. Frank Ableson'', ''Robi Sen'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (3,'1617290084','Specification by Example','[''Gojko Adzic'']','[''Software Engineering'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (4,'1933988746','Flex 3 in Action','[''Tariq Ahmed with Jon Hirschi'', ''Faisal Abid'']','[''Internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (5,'1935182420','Flex 4 in Action','[''Tariq Ahmed'', ''Dan Orlando'', ''John C. Bland II'', ''Joel Hooks'']','[''Internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (6,'1933988312','Collective Intelligence in Action','[''Satnam Alag'']','[''Internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (7,'1933988320','Zend Framework in Action','[''Rob Allen'', ''Nick Lo'', ''Steven Brown'']','[''Web Development'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (8,'1933988797','Flex on Java','[''Bernerd Allmon'', ''Jeremy Anderson'']','[''Internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (9,'1935182234','Griffon in Action','[''Andres Almiray'', ''Danno Ferrin'', '''', ''James Shingler'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (10,'193518217X','OSGi in Depth','[''Alexandre de Castro Alves'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (11,'1933988509','Flexible Rails','[''Peter Armstrong'']','[''Web Development'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (13,'1933988762','Hello! Flex 4','[''Peter Armstrong'']','[''Internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (14,'1884777384','Coffeehouse','[''Levi Asher'', ''Christian Crumlish'']','[''Miscellaneous'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (15,'1933988592','Team Foundation Server 2008 in Action','[''Jamil Azher'']','[''Microsoft .NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (16,'1933988711','Brownfield Application Development in .NET','[''Kyle Baley'', ''Donald Belcham'']','[''Microsoft'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (17,'1935182870','MongoDB in Action','[''Kyle Banker'']','[''Next Generation Databases'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (18,'1884777686','Distributed Application Development with PowerBuilder 6.0','[''Michael J. Barlotta'']','[''PowerBuilder'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (19,'1884777864','Jaguar Development with PowerBuilder 7','[''Michael Barlotta'']','[''PowerBuilder'', ''Client-Server'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (20,'1884777686','Taming Jaguar','[''Michael J. Barlotta'', ''Jason R. Weiss'']','[''PowerBuilder'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (21,'1884777902','3D User Interfaces with Java 3D','[''Jon Barrilleaux'']','[''Java'', ''Computer Graphics'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (22,'193239415X','Hibernate in Action','[''Christian Bauer'', ''Gavin King'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (23,NULL,'Hibernate in Action (Chinese Edition)','[''Christian Bauer'', ''Gavin King'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (24,'1932394885','Java Persistence with Hibernate','[''Christian Bauer'', ''Gavin King'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (25,'1930110529','JSTL in Action','[''Shawn Bayern'']','[''Internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (26,'1932394826','iBATIS in Action','[''Clinton Begin'', ''Brandon Goodin'', ''Larry Meadors'']','[''Web Development'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (27,'133046192','Designing Hard Software','[''Douglas W. Bennett'']','[''Object-Oriented Programming'', ''S'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (28,'1933988649','Hibernate Search in Action','[''Emmanuel Bernard'', ''John Griffin'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (29,'1933988355','jQuery in Action','[''Bear Bibeault'', ''Yehuda Katz'']','[''Web Development'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (30,'1935182323','jQuery in Action, Second Edition','[''Bear Bibeault'', ''Yehuda Katz'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (31,'1884777295','Building Secure and Reliable Network Applications','[''Kenneth P. Birman'']','[''Networking'', ''Theory'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (32,'1932394699','Ruby for Rails','[''David A. Black'']','[''Web Development'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (33,'1933988657','The Well-Grounded Rubyist','[''David A. Black'']','[''Programming'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (35,'1933988452','Website Owner''s Manual','[''Paul A. Boag'']','[''Internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (36,'1935182463','ASP.NET 4.0 in Practice','[''Daniele Bochicchio'', ''Stefano Mostarda'', '''', ''Marco De Sanctis'']','[''Microsoft .NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (37,'1935182080','Hello! Python','[''Anthony Briggs'']','[''Python'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (38,'1884777554','PFC Programmer''s Reference Manual','[''Richard Brooks'']','[''PowerBuilder'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (39,'133034054','Graphics File Formats','[''C. Wayne Brown'', ''Barry J. Shepherd'']','[''Computer Graphics'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (40,'131723979','Visual Object Oriented Programming','[''Margaret M. Burnett'', ''Adele Goldberg'', '''', ''Ted G. Lewis'']','[''Programming'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (41,'1617291269','iOS in Practice','[''Bear P. Cahill'']','[''Mobile Technology'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (42,'193398886X','iPhone in Action','[''Christopher Allen'', ''Shannon Appelcline'']','[''Web Development'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (43,'1933988428','Silverlight 2 in Action','[''Chad A. Campbell'', ''John Stockton'']','[''Microsoft .NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (45,'193518220X','The Quick Python Book, Second Edition','[''Naomi R. Ceder'']','[''Python'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (46,'1884777600','Internet and Intranet Applications with PowerBuilder 6','[''Tom Cervenka'']','[''PowerBuilder'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (48,'188477752X','Practical Methods for Your Year 2000 Problem','[''Robert Chapman'']','[''Business'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (51,'1884777368','Mobile Agents','[''William R. Cockayne and Michael Zyda'', ''editors'']','[''Internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (52,'1935182307','Spring Dynamic Modules in Action','[''Arnaud Cogoluegnes'', ''Thierry Templier'', '''', ''Andy Piper'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (53,'193398872X','SQL Server 2008 Administration in Action','[''Rod Colledge'']','[''Microsoft'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (54,'1935182927','Android in Practice','[''Charlie Collins'', ''Michael D. Galpin'', '''', ''Matthias Kaeppler'']','[''Mobile Technology'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (55,'1884777791','Object Oriented Perl','[''Damian Conway'']','[''Object-Oriented Programming'', ''P'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (56,'1933988290','GWT in Practice','[''Robert Cooper'', ''Charles Collins'']','[''Web Development'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (59,'1932394613','Ajax in Action','[''Dave Crane'', ''Eric Pascarello with Darren James'']','[''XML'', ''Internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (60,'1932394990','Ajax in Practice','[''Dave Crane'', ''Jord Sonneveld and Bear Bibeault with Ted Goddard'', ''Chris Gray'', ''Ram Venkataraman'', ''Joe Walker'']','[''Web Development'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (61,'1933988037','Prototype and Scriptaculous in Action','[''Dave Crane'', ''Bear Bibeault with Tom Locke'']','[''Web Development'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (63,'1932394583','POJOs in Action','[''Chris Richardson'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (64,'1930110006','Data Munging with Perl','[''David Cross'']','[''Perl'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (65,'1935182897','Hello! HTML5 & CSS3','[''Rob Crowther'']','[''Internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (66,'1933988401','Seam in Action','[''Dan Allen'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (67,'1932394982','Wicket in Action','[''Martijn Dashorst'', ''Eelco Hillenius'']','[''Web Development'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (68,'1933988541','Open Source SOA','[''Jeff Davis'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (69,'193398807X','Struts 2 in Action','[''Donald Brown'', ''Chad Michael Davis'', '''', ''Scott Stanlick'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (70,'1884777929','Essential Guide to Peoplesoft Development and Customization','[''Tony DeLia'', ''Galina Landres'', ''Isidor Rivera'', ''Prakash Sankaran'']','[''Client-Server'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (71,'1930110545','.NET Multithreading','[''Alan Dennis'']','[''Microsoft .NET'', ''Internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (72,'1932394389','SCWCD Exam Study Kit Second Edition','[''Hanumant Deshmukh'', ''Jignesh Malavia'', '''', ''Matthew Scarpino'']','[''Internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (73,'193518296X','Spring Roo in Action','[''Ken Rimple'', ''Srini Penchikala'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (74,'1617290270','SOA Governance in Action','[''Jos Dirksen'']','[''java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (75,'1932394494','RSS and Atom in Action','[''Dave Johnson'']','[''Internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (76,'1930110405','LDAP Programming, Management and Integration','[''Clayton Donley'']','[''Internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (77,'1933988967','Mule in Action','[''David Dossot'', "John D''Emic"]','[''Java'', ''Software Engineering'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (79,'1884777678','Java Foundation Classes','[''Stephen C. Drye'', ''William C. Wake'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (117,'1932394524k-e','Managing Components with Modeler','[''Vikram Goyal'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (118,'1932394524l-e','Command-line Processing with CLI','[''Vikram Goyal'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (119,'1932394524m-e','Understanding and Using Chain','[''Vikram Goyal'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (120,'1932394524n-e','Working with the Logging and Discovery Components','[''Vikram Goyal'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (121,'1932394524b-e','Uploading files with FileUpload','[''Vikram Goyal'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (122,'1932394524c-e','Handling Protocols with the Net Component','[''Vikram Goyal'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (123,'1932394524d-e','XML Parsing with Digester','[''Vikram Goyal'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (124,'1932394524e-e','JXPath and Betwixt: Working with XML','[''Vikram Goyal'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (125,'1932394524f-e','Validating Data with Validator','[''Vikram Goyal'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (126,'1932394524g-e','Enhancing Java Core Libraries with Collections','[''Vikram Goyal'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (127,'1932394524h-e','Enhancing Java Core Libraries with BeanUtils and Lang','[''Vikram Goyal'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (128,'1932394524i-e','Pool and DBCP: Creating and Using Object Pools','[''Vikram Goyal'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (129,'1884777813','Python and Tkinter Programming','[''John E. Grayson'']','[''Python'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (130,'1930110197','Microsoft.NET for Programmers','[''Fergal Grimes'']','[''Microsoft .NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (131,'1933988932','Grails in Action','[''Glen Smith'', ''Peter Ledbrook'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (132,'1884777759','Up to Speed with Swing, Second Edition','[''Steven Gutz'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (133,'1933988916','OSGi in Action','[''Richard S. Hall'', ''Karl Pauls'', ''Stuart McCulloch'', '''', ''David Savage'']','[''Internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (135,'1933988231','GWT in Action','[''Robert Hanson'', ''Adam Tacy'']','[''Internet'', ''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (136,'1884777740','The Quick Python Book','[''Daryl Harms'', ''Kenneth McDonald'']','[''Python'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (137,'1933988754','SharePoint 2010 Site Owner''s Manual','[''Yvonne M. Harryman'']','[''Microsoft .NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (139,'1930110588','Java Development with Ant','[''Erik Hatcher'', ''Steve Loughran'']','[''Java'', ''Internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (140,'1932394281','Lucene in Action','[''Erik Hatcher'', ''Otis Gospodnetic'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (141,'1933988177','Lucene in Action, Second Edition','[''Erik Hatcher'', ''Otis Gospodnetic'', '''', ''Michael McCandless'']','[''Java'', ''Open Source'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (142,'1884777708','PowerBuilder 6.0 Questions & Answers','[''Tim Hatton'']','[''PowerBuilder'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (143,'1884777538','The Awesome Power of PowerJ','[''Tim Hatton'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (144,'1884777546','The Awesome Power of Power++','[''Tim Hatton'']','[''PowerBuilder'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (145,'193518248X','Azure in Action','[''Chris Hay'', ''Brian H. Prince'']','[''Microsoft .NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (146,'1935182412','Distributed Agile in Action','[''Vikas Hazrati'', ''Balaji D Loganathan'']','[''Software Engineering'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (147,'1617290262','Metaprogramming in .NET','[''Kevin Hazzard'', ''Jason Bock'']','[''Microsoft/.NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (148,NULL,'Portlets and Apache Portals','[''Stefan Hepper'', ''Peter Fischer'', ''Stephan Hesmer'', ''Richard Jacob'', ''David Sean Taylor'']','[''Java'']',1);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (149,'1930110979','Code Generation in Action','[''Jack Herrington'']','[''Programming'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (150,'138582262','Illustrated Guide to HTTP','[''Paul S. Hethmon'']','[''Internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (152,'1935182633','Agile ALM','[''Michael Hüttermann'']','[''Software Engineering'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (153,'188477749X','Java Network Programming, Second Edition','[''Merlin Hughes'', ''Michael Shoffner'', '''', ''Derek Hamner'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (154,'1932394249','Struts in Action','[''Ted N. Husted'', ''Cedric Dumoulin'', ''George Franciscus'', ''David Winterfeldt'']','[''Java'', ''Internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (155,'1935182366','Camel in Action','[''Claus Ibsen'', ''Jonathan Anstey'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (156,'193398838X','Taming Text','[''Grant S. Ingersoll'', ''Thomas S. Morton'', '''', ''Andrew L. Farris'']','[''Software Engineering'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (158,'1933988029','JBoss in Action','[''Javid Jamae'', ''Peter Johnson'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (159,'1933988398','Gnuplot in Action','[''Philipp K. Janert'']','[''Computer Graphics'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (160,'1930110820','Extending and Embedding Perl','[''Tim Jenness'', ''Simon Cozens'']','[''Perl'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (161,'1617290017','iOS 4 in Action','[''Jocelyn Harrington'', ''Brandon Trebitowski'', ''Christopher Allen'', '''', ''Shannon Appelcline'']','[''Mobile Technology'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (162,'1884777805','Elements of Programming with Perl','[''Andrew L. Johnson'']','[''Perl'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (163,'1617290211','Learn Windows PowerShell in a Month of Lunches','[''Don Jones'']','[''Microsoft .NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (164,'1935182390','R in Action','[''Robert I. Kabacoff'']','[''Software Engineering'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (165,'9.78E+12','Android in Practice','[''Matthias Kaeppler'', ''Michael D. Galpin'', ''Charlie Collins'']','[''Mobile Technology'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (167,'1932394680','SOA Security','[''Ramarao Kanneganti'', ''Prasad A. Chodavarapu'']','[''Software Engineering'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (168,'1935182277','Rails 3 in Action','[''Ryan Bigg'', ''Yehuda Katz'']','[''Internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (169,'1935182552','Continuous Integration in .NET','[''Marcin Kawalerowicz'', ''Craig Berntson'']','[''Microsoft .NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (170,'1932394133','Technology Paradise Lost','[''Erik Keller'']','[''Business'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (172,'1930110057','Kermit 95+','[''Kermit Project at Columbia University'']','[''Internet'', ''Networking'', ''Miscella'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (173,'1932394834','Laszlo in Action','[''Norman Klein'', ''Max Carlson with Glenn MacEwen'']','[''Web Development'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (174,'1932394842','Groovy in Action','[''Dierk Koenig with Andrew Glover'', ''Paul King'', ''Guillaume Laforge'', ''Jon Skeet'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (175,'1935182447','Groovy in Action, Second Edition','[''Dierk König'', ''Guillaume Laforge'', ''Paul King'', ''Cédric Champeau'', "Hamlet D''Arcy", ''Erik Pragt'', '''', ''Jon Skeet'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (176,'132612313','Object Technology Centers of Excellence','[''Timothy D. Korson'', ''Vijay K. Vaishnavi'']','[''Object-Technology Programming'', '''']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (177,'1932394850','Test Driven','[''Lasse Koskela'']','[''Software Engineering'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (178,'1935182579','Effective Unit Testing','[''Lasse Koskela'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (179,'1935182943','Making Java Groovy','[''Kenneth A. Kousen'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (180,'1884777473','The Awesome Power of Direct3D/DirectX','[''Peter J. Kovach'']','[''Computer Graphics'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (181,'1884777597','Practical Software Requirements','[''Benjamin L. Kovitz'']','[''Software Engineering'', ''Theory'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (182,'1932394923','NHibernate in Action','[''Pierre Henri Kuate'', ''Tobin Harris'', ''Christian Bauer'', '''', ''Gavin King'']','[''Microsoft .NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (183,'1932394222','Microsoft Reporting Services in Action','[''Teo Lachev'']','[''Microsoft .NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (184,'1930110936','AspectJ in Action','[''Ramnivas Laddad'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (185,'1933988053','AspectJ in Action, Second Edition','[''Ramnivas Laddad'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (186,'1935182196','Hadoop in Action','[''Chuck Lam'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (187,'1884777775','SQR in PeopleSoft and Other Applications','[''Galina'', ''Vlad Landres'']','[''Business'', ''Client-Server'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (188,'1932394001','SQR in PeopleSoft and Other Applications, Second Edition','[''Galina Landres'', ''Vlad Landres'']','[''Business'', ''Client-Server'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (189,'1935182250','F# in Action','[''Amanda Laucher'']','[''Microsoft .NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (190,'1933988894','Tuscany SCA in Action','[''Simon Laws'', ''Mark Combellack'', ''Raymond Feng'', ''Haleh Mahbod'', ''Simon Nash'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (192,'1884777082','Client/Server Yellow Pages','[''Compiled'', ''introduced by Ted Lewis'']','[''Client-Server'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (193,'1884777066','Object Oriented Application Frameworks','[''Ted Lewis'', ''friends'']','[''Object-Oriented Programming'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (194,'1932394117','Tapestry in Action','[''Howard M. Lewis Ship'']','[''Java'', ''Internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (195,'1932394532','WebWork in Action','[''Patrick Lightbody'', ''Jason Carreira'']','[''internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (196,'1935182498','MacRuby in Action','[''Brendan G. Lim with Jerry Cheung'', ''Jeremy McAnally'']','[''Programming'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (197,'1933988789','Erlang and OTP in Action','[''Martin Logan'', ''Eric Merritt'', '''', ''Richard Carlsson'']','[''Programming'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (198,'1933988819','SharePoint 2007 Developer''s Guide to Business Data Catalog','[''Brett Lonsdale'', ''Nick Swan'']','[''Microsoft .NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (199,'133964256','Doing IT Right','[''Harold Lorin'']','[''Business'', ''Software Engineering'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (200,'1933988487','Adobe AIR in Action','[''Joey Lott'', ''Kathryn Rotondo'', ''Sam Ahn'', ''Ashley Atkins'']','[''Web Development'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (201,'193239480X','Ant in Action','[''Steve Loughran'', ''Erik Hatcher'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (202,'193518234X','Restlet in Action','[''Jerome Louvel'', ''Thierry Boileau'', '''', ''Philippe Mougin'']','[''Internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (203,'1932394796','iText in Action','[''Bruno Lowagie'']','[''Web Development'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (204,'1935182617','iText in Action, Second Edition','[''Bruno Lowagie'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (205,'138412146','Power-3D','[''Kyle Lussier'']','[''Computer Graphics'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (206,'131271687','SNA and TCP/IP Enterprise Networking','[''Daniel C. Lynch'', ''James P. Gray'', ''and Edward Rabinovitch'', ''editors'']','[''Software Engineering'', ''Theory'']',1);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (208,'1932394478','Subversion in Action','[''Jeffrey Machols'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (209,'1932394508','Minimal Perl','[''Tim Maher'']','[''Perl'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (210,'1884777651','Distributed Programming with Java','[''Qusay H. Mahmoud'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (211,'013319955X','Comprehensive Networking Glossary and Acronym Guide','[''Gary Scott Malkin'']','[''Internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (212,'1932394125','JavaServer Faces in Action','[''Kito D. Mann'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (213,'1933988169','LINQ in Action','[''Fabrice Marguerie'', ''Steve Eichert'', ''Jim Wooley'']','[''Microsoft .NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (214,'132869985','Internet BBSs','[''Richard Scott Mark'']','[''Internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (215,'1933988665','Algorithms of the Intelligent Web','[''Haralambos Marmanis'', ''Dmitry Babenko'']','[''Web Development'']',1);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (216,'1930110995','JUnit in Action','[''Vincent Massol with Ted Husted'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (217,'1935182854','Tika in Action','[''Chris A. Mattmann'', ''Jukka L. Zitting'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (218,'1933988479','Ruby in Practice','[''Jeremy McAnally'', ''Assaf Arkin'']','[''Programming'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (219,'1884777481','Inside LotusScript','[''Joe McGinn'']','[''Business'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (220,'1884777449','Maximum MIDI','[''Paul Messick'']','[''Programming'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (221,'132621894','Planning and Managing ATM Networks','[''Daniel Minoli'', ''Thomas W. Golway'', '''', ''Norris P. Smith'']','[''Client-Server'', ''Networking'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (222,'137353006','Client/Server Applications on ATM Networks','[''Daniel Minoli'', ''Andrew Schmidt'']','[''Client-Server'', ''Networking'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (223,'1933988991','JavaFX in Action','[''Simon Morris'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (224,'1935182188','Entity Framework 4 in Action','[''Stefano Mostarda'', ''Marco De Sanctis'', '''', ''Daniele Bochicchio'']','[''Microsoft .NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (225,'193239477X','ASP.NET 2.0 Web Parts in Action','[''Darren Neimke'']','[''Microsoft'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (226,'1617290149','Sass and Compass in Action','[''Wynn Netherland'', ''Nathan Weizenbaum'', ''Chris Eppstein'', '''', ''Brandon Mathis'']','[''Web Development'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (227,'1884777503','Core OWL 5.0','[''Ted Neward'']','[''Programming'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (228,'1884777465','Advanced OWL 5.0','[''Ted Neward'']','[''Programming'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (229,'1884777716','Server-Based Java Programming','[''Ted Neward'']','[''Java'', ''Client-Server'', ''Internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (230,'1935182048','SQL Server MVP Deep Dives','[''Contributions from 53 SQL Server MVPs'', ''Edited by Paul Nielsen'', ''Kalen Delaney'', ''Greg Low'', ''Adam Machanic'', ''Paul S. Randal'', '''', ''Kimberly L. Tripp'']','[''Microsoft .NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (231,'9.78E+12','SQL Server MVP Deep Dives','[''Contributions from 53 SQL Server MVPs; Edited by Paul Nielsen'', ''Kalen Delaney'', ''Greg Low'', ''Adam Machanic'', ''Paul S. Randal'', '''', ''Kimberly L. Tripp'']','[''Microsoft .NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (232,'9.78E+12','SQL Server MVP Deep Dives','[''Paul Nielsen'', ''Kalen Delaney'', ''Greg Low'', ''Adam Machanic'', ''Paul S. Randal'', '''', ''Kimberly L. Tripp'']','[''Microsoft .NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (233,'1935182269','PostGIS in Action','[''Regina O. Obe'', ''Leo S. Hsu'']','[''Internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (235,'1930110855','Programming Mac OS X','["Kevin O''Malley"]','[''Programming'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (236,'1933988274','The Art of Unit Testing','[''Roy Osherove'']','[''Software Engineering'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (237,'1935182684','Mahout in Action','[''Sean Owen'', ''Robin Anil'', ''Ted Dunning'', '''', ''Ellen Friedman'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (238,'1933988622','ASP.NET MVC in Action','[''Jeffrey Palermo'', ''Ben Scheirman'', '''', ''Jimmy Bogard'']','[''Microsoft .NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (239,'193518279X','ASP.NET MVC 2 in Action','[''Jeffrey Palermo'', ''Ben Scheirman'', ''Jimmy Bogard'', ''Eric Hexter'', '''', ''Matthew Hinze'']','[''Microsoft .NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (240,'1617290416','ASP.NET MVC 4 in Action','[''Jeffrey Palermo'', ''Jimmy Bogard'', ''Eric Hexter'', ''Matthew Hinze'', '''', ''Jeremy Skinner'']','[''Microsoft .NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (241,'1933988347','EJB 3 in Action','[''Debu Panda'', ''Reza Rahman'', ''Derek Lane'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (242,'1935182994','EJB 3 in Action, Second Edition','[''Debu Panda'', ''Reza Rahman'', ''Ryan Cuprak'', '''', ''Michael Remijan'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (243,'1932394206','Explorer''s Guide to the Semantic Web','[''Thomas B. Passin'']','[''Internet'', ''Theory'', ''XML'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (244,'1884777767','Practical LotusScript','[''Anthony Patton'']','[''Business'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (245,'1930110049','Domino Development with Java','[''Anthony Patton'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (246,'1932394907','Windows PowerShell in Action','[''Bruce Payette'']','[''Microsoft'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (247,'1935182137','Windows PowerShell in Action, Second Edition','[''Bruce Payette'']','[''Microsoft'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (248,'1935182374','Silverlight 4 in Action, Revised Edition','[''Pete Brown'']','[''Microsoft .NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (249,'1617290319','Silverlight 5 in Action','[''Pete Brown'']','[''Microsoft'', ''.NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (250,'1932394419','Hibernate Quickly','[''Patrick Peak'', ''Nick Heudecker'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (251,'1935182625','Generative Art','[''Matt Pearson'']','[''Algorithmic Art'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (252,'1617290092','Windows Phone 7 in Action','[''Timothy Binkley-Jones'', ''Massimo Perga'', '''', ''Michael Sync'']','[''Mobile Technology'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (253,'1935182803','Lift in Action','[''Timothy Perrett'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (254,'1930110065','Web Development with Apache and Perl','[''Theo Petersen'']','[''Perl'', ''Client-Server'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (255,'1933988924','Real-World Functional Programming','[''Tomas Petricek with Jon Skeet'']','[''Microsoft .NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (256,'1617290181','Machine Learning in Action','[''Peter Harrington'']','[''Software Engineering'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (257,'193398855X','Dependency Injection','[''Dhanji R. Prasanna'']','[''Microsoft .NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (258,'1932394591','Understanding Enterprise SOA','[''Eric Pulier and Hugh Taylor'', ''Foreword by Paul Gaffney'']','[''Theory'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (259,'1933988215','Open-Source ESBs in Action','[''Tijs Rademakers'', ''Jos Dirksen'']','[''Business'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (260,'1617290122','Activiti in Action','[''Tijs Rademakers'']','[''Software Engineering'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (261,'1933988606','DSLs in Boo: Domain-Specific Languages in .NET','[''Oren Eini writing as Ayende Rahien'']','[''Microsoft .NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (262,'1932394230','JUnit Recipes','[''J. B. Rainsberger with contributions by Scott Stirling'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (263,'1932394621','wxPython in Action','[''Noel Rappin'', ''Robin Dunn'']','[''Python'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (264,'1935182595','Clojure in Action','[''Amit Rathore'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (265,'1935182757','Scala in Action','[''Nilanjan Raychaudhuri'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (266,'134529308','Working with Objects','[''Trygve Reenskaug'']','[''Object-Oriented Programming'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (267,'1932394753','PHP in Action','[''Dagfinn Reiersøl with Marcus Baker'', ''Chris Shiflett'']','[''PHP'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (269,'193398869X','Secrets of the JavaScript Ninja','[''John Resig'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (270,'132623129','Microsoft Office Essentials','[''Ronny Richardson'']','[''Business'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (271,'1884777848','Swing','[''Matthew Robinson'', ''Pavel Vorobiev'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (272,'193011088X','Swing Second Edition','[]','[''Java'', ''Internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (273,'1884777562','The Awesome Power of Java Beans','[''Lawrence H. Rodrigues'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (274,'013268327X','Personal Videoconferencing','[''Evan Rosen'']','[''Networking'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (275,'1935182528','The Cloud at Your Service','[''Jothy Rosenberg'', ''Arthur Mateos'']','[''Internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (276,'1884777694','Implementing Elliptic Curve Cryptography','[''Michael Rosing'']','[''Theory'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (277,'1933988266','SOA Patterns','[''Arnon Rotem-Gal-Oz'']','[''SOA'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (278,'1933988495','Hello World!','[''Warren D. Sande'', ''Carter Sande'']','[''Programming'', ''Python'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (279,'1932394400','SCBCD Exam Study Kit','[''Paul Sanghera'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (280,'1935182544','Portlets in Action','[''Ashish Sarin'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (281,'1932394273','SWT/JFace in Action','[''Matthew Scarpino'', ''Stephen Holder'', ''Stanford Ng'', '''', ''Laurent Mihalkovic'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (282,'1617290173','OpenCL in Action','[''Matthew Scarpino'']','[''Programming'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (283,'138892709','Multiprotocol over ATM','[''Andrew Schmidt'', ''Daniel Minoli'']','[''Internet'', ''Networking'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (284,'1935182501','Dependency Injection in .NET','[''Mark Seemann'']','[''Microsoft .NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (285,'1930110359','Java 3D Programming','[''Daniel Selman'']','[''Java'', ''Internet'', ''Computer Graph'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (286,'193518282X','Liferay in Action','[''Richard Sezov'', ''Jr'']','[''Internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (287,'193011009X','JSP Tag Libraries','[''Gal Shachor'', ''Adam Chace'', ''Magnus Rydin'']','[''Java'', ''Internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (289,'1930110464','Instant Messaging in Java','[''Iain Shigeoka'']','[''Internet'', ''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (290,'1884777392','Java Applets and Channels Without Programming','[''Ronny Richardson'', ''Michael Shoffner'', ''Marq Singer'', ''Bruce Murray'', '''', ''Jack Gambol'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (291,'1935182005','PowerShell in Practice','[''Richard Siddaway'']','[''Microsoft .NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (292,'1617290114','PowerShell and WMI','[''Richard Siddaway'']','[''Microsoft .NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (293,'132632942','Making Sense of Java','[''Bruce Simpson'', ''John Mitchell'', ''Brian Christeson'', ''Rehan Zaidi'', '''', ''Jonathan Levine'']','[''Java'', ''Business'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (294,'1932394818','C++/CLI in Action','[''Nishant Sivakumar'']','[''Microsoft'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (295,'1933988363','C# in Depth','[''Jon Skeet'']','[''Microsoft .NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (296,'1935182471','C# in Depth, Second Edition','[''Jon Skeet'']','[''Microsoft .NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (297,'1884777589','Magical A-Life Avatars','[''Peter Small'']','[''Internet'', ''Theory'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (298,'1933988258','Becoming Agile','[''Greg Smith'', ''Ahmed Sidky'']','[''Software Engineering'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (299,'1933988940','ActiveMQ in Action','[''Bruce Snyder'', ''Dejan Bosanac'', '''', ''Rob Davies'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (300,'138411808','Implementing PeopleSoft Financials','[''Early Stephens'']','[''Business'', ''Client-Server'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (302,'1935182730','SQL Server DMVs in Action','[''Ian W. Stirk'']','[''Microsoft .NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (303,'1935182706','Scala in Depth','[''Joshua D. Suereth'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (304,'1930110561','JMX in Action','[''Benjamin G. Sullins'', ''Mark B. Whipple'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (305,'1930110944','EJB Cookbook','[''Benjamin G. Sullins'', ''Mark B. Whipple'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (306,'1935182846','GWT in Action, Second Edition','[''Adam Tacy'', ''Robert Hanson'', ''Jason Essington'', '''', ''Anna Tökke'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (307,'1935182021','JUnit in Action, Second Edition','[''Petar Tahchiev'', ''Felipe Leme'', ''Vincent Massol'', '''', ''Gary Gregory'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (308,'193011043X','Bitter Java','[''Bruce A. Tate'']','[''Java'', ''Business'', ''Client Server'', '''']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (309,'1930110952','Bitter EJB','[''Bruce Tate'', ''Mike Clark'', ''Bob Lee'', ''Patrick Linskey'']','[''Java'', ''Internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (310,'1935182951','Spring Batch in Action','[''Arnaud Cogoluegnes'', ''Thierry Templier'', ''Gary Gregory'', ''Olivier Bazoud'']','[''In Action'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (312,'1930110456','JDK 1.4 Tutorial','[''Gregory M. Travis'']','[''Java'', ''Internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (313,'1935182587','iPhone and iPad in Action','[''Brandon Trebitowski'', ''Christopher Allen'', '''', ''Shannon Appelcline'']','[''Mobile Technology'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (314,'1932394761','SQL Server 2005 Reporting Services in Action','[''Bret Updegraff'']','[''Microsoft'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (315,'1935182129','Ten Years of UserFriendly.Org','[''JD "Illiad" Frazer'']','[''Miscellaneous'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (316,'1930110022','Graphics Programming with Perl','[''Martien Verbruggen'']','[''Computer Graphics'', ''Perl'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (317,'1935182978','RabbitMQ in Action','[''Alvaro Videla'', ''Jason J.W. Williams'']','[''Software Engineering'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (318,'1932394052','XDoclet in Action','[''Craig Walls'', ''Norman Richards'']','[''XML'', ''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (319,'1932394354','Spring in Action','[''Craig Walls'', ''Ryan Breidenbach'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (320,'1933988134','Spring in Action, Second Edition','[''Craig Walls with Ryan Breidenbach'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (321,'1935182358','Spring in Action, Third Edition','[''Craig Walls'']','[''Java'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (325,'1935182056','Spring in Practice','[''Willie Wheeler with Joshua White'']','[''Java'', ''Software Development'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (327,'1930110332','Java 2 Micro Edition','[''James P. White'', ''David A. Hemphill'']','[''Java'', ''Internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (328,'1935182714','SharePoint 2010 Workflows in Action','[''Phil Wicklund'']','[''Microsoft .NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (329,'1935182773','SharePoint 2010 Web Parts in Action','[''Wictor Wilén'']','[''Microsoft .NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (330,'1933988770','C++ Concurrency in Action','[''Anthony Williams'']','[''Microsoft .NET'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (331,'188477766X','Java Servlets by Example','[''Alan R. Williamson'']','[''Java'', ''Internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (332,'1884777872','XML Programming with VB and ASP','[''Mark Wilson'', ''Tracey Wilson'']','[''XML'', ''Internet'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (334,'1884777783','Oracle8i Database Administration','[''Noel Yuhanna'']','[''Client-Server'', ''Networking'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (335,'9.78E+12','The Engaging Web','[''Gabe Zichermann'', ''Chris Cunningham'']','[''Web Development'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (512,'1617290130','Enterprise OSGi In Action','[''Holly Cummins'', ''Timothy Ward'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (513,'1617290327','Ext JS in Action, Second Edition','[''Jesus Garcia'', ''Grgur Grisogono'', '''', ''Jacob K. Andresen'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (514,'1617290505','Android in Action, Third Edition','[''W. Frank Ableson'', ''Robi Sen'', ''Chris King'', ''C. Enrique Ortiz'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (515,'1617290246','Arduino in Action','[''Martin Evans'', ''Joshua Noble'', '''', ''Jordan Hochenbaum'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (516,'1617290572','Node.js in Action','[''Mike Cantelon'', ''Marc Harter'', ''T.J. Holowaychuk'', '''', ''Nathan Rajlich'']','[''Web Development'']',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (517,'1617290548','Third-Party JavaScript','[''Ben Vinegar'', ''Anton Kovalyov'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (519,'020152029X','Multimedia Computing','[''Matthew E. Hodges'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (520,'1884777996','Web Development with JavaServer Pages','[''Duane K. Fields'', ''Mark A. Kolb'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (521,'1884777643','Up to Speed with Swing','[''Steven J. Gutz'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (522,'193239429X','Manager''s Guide to Open Source','[''Maria Winslow'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (523,'1930110421','Programming Web Services with Java','[''Ajamu A. Wesley'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (525,'132612496','TCP/IP Programming for OS/2','[''Steven J. Gutz'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (530,'013889213X','Implementing SAP R/3, Second Edition','[]','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (531,'1884777228','Implementing SAP R/3','[]','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (532,'1884777147','Using C-Kermit: Communication Software','[]','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (533,'1930110596','SCWCD Exam Study Kit','[''Hanumant Deshmukh'', ''Jignesh Malavia'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (549,'1617290386','Unit Testing in C++','[''Bruce Trask'', ''Angel Roman'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (550,'1617290343','Big Data','[''Nathan Marz'', ''James Warren'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (551,'1617290629','CoffeeScript in Action','[''Patrick Lee'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (559,'1617290475','SQL Server MVP Deep Dives, Volume 2','[''Kalen Delaney'', ''Louis Davidson'', ''Greg Low'', ''Brad McGehee'', ''Paul Nielsen'', ''Paul Randal'', '''', ''Kimberly Tripp'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (560,'1617290491','HTML5 in Action','[''Rob Crowther'', ''Joe Lennon'', ''Ash Blue'', '''', ''Greg Wanish'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (562,'1617290459','Java Persistence with Hibernate, Second Edition','[''Christian Bauer'', ''Gavin King'', '''', ''Gary Gregory'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (566,'1617290238','Hadoop in Practice','[''Alex Holmes'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (569,'1617290521','HBase in Action','[''Nicholas Dimiduk'', ''Amandeep Khurana'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (571,'1617290610','Flex Mobile in Action','[''Jonathan Campos'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (577,'1617290432','HTML5 for .NET Developers','[''Jim Jackson'', ''II'', ''Ian Gilman'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (580,'1617290564','50 Android Hacks','[''Carlos M. Sessa'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (591,'1617290556','PowerShell in Depth','[''Don Jones'', ''Richard Siddaway'', '''', ''Jeffery Hicks'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (599,'1617290165','Augmented Reality Revealed','[''Robert A. Rice Jr.'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (607,'1617290599','Building Well-Structured JavaScript Applications','[''Julio C. Ody'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (611,'1617290394','Linked Data','[''David Wood'', ''Marsha Zaidman'', ''Luke Ruth'', ''with Michael Hausenblas'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (620,'1617290823','Mule in Action, Second Edition','[''David Dossot'', "John D''Emic", '''', ''Victor Romero'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (624,'1617290750','Single Page Web Applications','[''Michael S. Mikowski'', ''Josh C. Powell'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (628,'1617290890','The Art of Unit Testing, Second Edition','[''Roy Osherove'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (629,'1617290904','Play for Java','[''Nicolas Leroux'', ''Sietse de Kaper'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (631,'1617290920','Hello World! Second Edition','[''Warren Sande'', ''Carter Sande'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (632,'1617290866','Dart in Action','[''Chris Buckett'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (634,'1617290858','Redis in Action','[''Josiah Carlson'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (636,'161729084X','Using the TI-83 Plus/TI-84 Plus','[''Christopher R. Mitchell'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (637,'1617290769','Neo4j in Action','[''Jonas Partner'', ''Aleksa Vukotic'', '''', ''Nicki Watt'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (639,'1617290777','Programming the TI-83 Plus/TI-84 Plus','[''Christopher R. Mitchell'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (640,'1617290653','Functional Programming in Scala','[''Paul Chiusano'', ''Rúnar Bjarnason'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (641,'1617290793','Play for Scala','[''Peter Hilton'', ''Erik Bakker'', '''', ''Francisco Canedo'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (642,'1617290939','Node.js in Practice','[''Alex Young'', ''Marc Harter'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (643,'1617290955','SonarQube in Action','[''G. Ann Campbell'', ''Patroklos P. Papapetrou'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (644,'1617290947','Windows Store App Development: C# and XAML','[''Peter M. Brown'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (645,'1617290971','Learn Windows IIS in a Month of Lunches','[''Jason C. Helmick'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (646,'161729098X','Mondrian in Action','[''William Back'', ''Nicholas Goodman'', '''', ''Julian Hyde'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (648,'1617291005','RabbitMQ in Depth','[''Gavin M. Roy'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (649,'1617291013','Akka in Action','[''Raymond Roestenburg'', ''Rob Bakker'', ''Rob Williams'', ''Steven Haines'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (650,'161729103X','Extending jQuery','[''Keith B. Wood'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (651,'1617291048','OCA Java SE 7 Programmer I Certification Guide','[''Mala Gupta'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (652,'1617291056','Kanban in Action','[''Marcus Hammarberg'', ''Joakim Sunden'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (653,'1617291021','Solr in Action','[''Trey Grainger'', ''Timothy Potter'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (655,'1617291072','Making Sense of NoSQL','[''Daniel G. McCreary'', ''Ann M. Kelly'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (656,'1884777864','Jaguar Development with PowerBuilder 7','[''MIchael Barlotta'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (657,'1617290963','Grails in Action, Second Edition','[''Glen Smith'', ''Peter Ledbrook'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (658,'1617291099','Rails 4 in Action','[''Ryan Bigg'', ''Yehuda Katz'', ''and Steve Klabnik'', '''']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (659,'1617291080','Learn Windows PowerShell in a Month of Lunches, Second Edition','[''Don Jones'', ''Jeffery D. Hicks'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (662,'1617291145','AOP in .NET','[''Matthew D. Groves'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (663,'1617291161','Learn PowerShell Toolmaking in a Month of Lunches','[''Don Jones'', ''Jeffery Hicks'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (664,'1617291153','CMIS and Apache Chemistry in Action','[''Florian Müller'', ''Jay Brown'', ''Jeff Potts'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (667,'1930110324','Action Guide (aka VB .NET)','[''Paul Messick'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (670,'1617291196','Learn Active Directory Management in a Month of Lunches','[''Richard Siddaway'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (671,'161729120X','Spring in Action, Fourth Edition','[''Craig Walls'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (672,'1617291218','The Mikado Method','[''Ola Ellnestam'', ''Daniel Brolund'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (676,'1617291242','The Responsive Web','[''Matthew Carver'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (677,'1617291250','Fast ASP.NET Websites','[''Dean Alan Hume'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (678,'1617291277','SBT in Action','[''Joshua Suereth'', ''Matthew Farwell'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (679,'1617291315','PowerShell Deep Dives','[''Edited by Jeffery Hicks'', ''Richard Siddaway'', ''Oisin Grehan'', '''', ''Aleksandar Nikolic'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (680,'1617291307','Gradle in Action','[''Benjamin Muschko'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (681,'1617291293','Scalatra in Action','[''Ivan Porto Carrero'', ''Ross A. Baker'', ''Dave Hrycyszyn'', ''Stefan Ollinger'', '''', ''Jared Armstrong'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (683,'1617291331','AngularJS in Action','[''Brian Ford'', ''Lukas Ruebbelke'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (684,'1617291358','Software Development Metrics','[''David Nicolette'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (685,'1617291323','F# Deep Dives','[''Tomas Petricek'', ''Phillip Trelford'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (686,'161729134X','C# in Depth, Third Edition','[''Jon Skeet'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (688,'1617291390','PostGIS in Action, Second Edition','[''Regina Obe'', ''Leo Hsu'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (689,'1617291382','R in Action, Second Edition','[''Robert Kabacoff'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (691,'1617291412','The Joy of Clojure, Second Edition','[''Michael Fogus'', ''Chris Houser'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (692,'1617291420','iOS 7 in Action','[''Brendan G. Lim'', ''Martin Conte Mac Donell'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (693,'1617291439','Hello App Inventor!','[''Paula Beer'', ''Carl Simmons'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (696,'1617291455','Ember.js in Action','[''Joachim Haagen Skeie'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (697,'1617291471','Netty in Action','[''Norman Maurer'', ''Courtney Robinson'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (699,'1617291501','RavenDB in Action','[''Itamar Syn-Hershko'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (700,'161729148X','OCP Java SE 7 Programmer II Certification Guide','[''Mala Gupta'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (702,'1617291536','Backbone.js in Action','[''Samuel M. Breed'', ''Cole Krumbholz'', '''', ''Phillip Whisenhunt'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (703,'1617291528','Clojure in Action, Second Edition','[''Amit Rathore'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (706,'1617291560','Practical Data Science with R','[''Nina Zumel'', ''John Mount'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (707,NULL,'Secrets of the JavaScript Ninja pBook upgrade','[]','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (711,'1617291617','ArcGIS Web Development','[''Rene Rubalcava'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (712,'1617291625','Elasticsearch in Action','[''Radu Gheorghe'', ''Matthew Lee Hinman'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (716,'1617291684','Learn SCCM 2012 in a Month of Lunches','[''James Bannan'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (717,'1617291706','Programming for Musicians and Digital Artists','[''Ajay Kapur'', ''Perry Cook'', ''Spencer Salazar'', '''', ''Ge Wang'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (719,'161729165X','BDD in Action','[''John F. Smart'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (723,'1617291374','Windows Phone 8 in Action','[''Timothy Binkley-Jones'', ''Massimo Perga'', ''Michael Sync'', ''Adam Benoit'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (724,'1617291749','Titanium Alloy in Action','[''Ricardo Alcocer'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (727,'1617291757','Giraph in Action','[''Claudio Martella'', ''Roman Shaposhnik'', '''', ''Dionysios Logothetis'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (728,'1617291692','The Well-Grounded Rubyist, Second Edition','[''David A. Black'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (729,'1617291781','Go in Action','[''Brian Ketelsen'', ''Erik St. Martin'', '''', ''William Kennedy'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (731,'1617291811','The Programmer''s Guide to Apache Thrift','[''Randy Abernethy'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (732,'1617291838','Grokking Functional Programming','[''Aslam Khan'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (733,'161729182X','CORS in Action','[''Monsur Hossain'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (736,'1617291803','Reactive Design Patterns','[''Roland Kuhn'', ''Jamie Allen'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (740,'1617291897','Storm Applied','[''Sean Allen'', ''Peter Pathirana'', '''', ''Matthew Jankowski'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (743,'1617291927','Real-World Machine Learning','[''Henrik Brink'', ''Joseph Richards'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (744,'1617291935','jQuery UI in Action','[''Theodore J. (T.J.) VanToll III'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (746,'1617291943','Web Components in Action','[''Chris Buckett'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (748,'1617291951','JavaScript Application Design','[''Nicolas G. Bevacqua'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (749,'1617291978','Git in Practice','[''Mike McQuaid'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (750,'1617291986','Impala in Action','[''Richard L. Saltzer'', ''Istvan Szegedi'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (751,'1617291994','Java 8 in Action','[''Raoul-Gabriel Urma'', ''Mario Fusco'', '''', ''Alan Mycroft'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (753,'161729201X','Elixir in Action','[''Saša Juric´'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (755,'1617291609','MongoDB in Action, Second Edition','[''Kyle Banker'', ''Peter Bakkum'', ''Tim Hawkins'', ''Shaun Verch'', '''', ''Douglas Garrett'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (757,'1617292036','Getting MEAN with Mongo, Express, Angular, and Node','[''Simon Holmes'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (761,'1617292079','jQuery in Action, Third Edition','[''Bear Bibeault'', ''Yehuda Katz'', '''', ''Aurelio De Rosa'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (764,'1617292117','D3.js in Action','[''Elijah Meeks'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (765,'1617292133','Learn SQL Server Administration in a Month of Lunches','[''Don Jones'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (766,'1617292141','Geoprocessing with Python','[''Chris Garrard'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (767,'161729215X','Barcodes with iOS','[''Oliver Drobnik'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (771,'1617292214','Chef in Action','[''Dimitri Aivaliotis'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (772,'1617292222','Hadoop in Practice, Second Edition','[''Alex Holmes'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (774,'1617292192','Oculus Rift in Action','[''Bradley Austin Davis'', ''Karen Bryla'', '''', ''Alex Benton'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (776,'1617292168','OpenStack in Action','[''Cody Bumgardner'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (777,'1617292184','PowerShell in Depth, Second Edition','[''Don Jones'', ''Jeffery Hicks'', '''', ''Richard Siddaway'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (785,'1617292338','Practical Probabilistic Programming','[''Avi Pfeffer'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (786,'161729232X','Unity in Action','[''Joseph Hocking'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (794,'1617292427','Express.js in Action','[''Evan M. Hahn'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (795,'1617292419','Learn Git in a Month of Lunches','[''Rick Umali'']','[]',0);
INSERT INTO Book(BookID,isbn,title,authors,categories,outOfCirculation) VALUES (796,'1617292435','Understanding SPAs','[''Emmit A. Scott'', ''Jr.'']','[]',0);
